name: Build and Push Docker Image

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract version from release tag
        id: extract_version
        run: |
          VERSION=${{ github.ref_name }}
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Build and tag Docker image
        run: |
          docker build -t discord-webhook-service .
          docker tag discord-webhook-service ${{ secrets.DOCKER_USERNAME }}/discord-webhook-service:${{ env.VERSION }}
          docker tag discord-webhook-service ${{ secrets.DOCKER_USERNAME }}/discord-webhook-service:latest

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/discord-webhook-service:${{ env.VERSION }}
          docker push ${{ secrets.DOCKER_USERNAME }}/discord-webhook-service:latest